title: "My Profile"
description: "Organised by my interests, blog posts, achievements and thoughts"
url: "https://MartinKalories.github.io"
baseurl: "/manavkalra"  # Change 'manavkalra' to your repository name if different